
version: "3.7"
services:
  ubuntu18:
    build:
      context: ./
    cap_add: 
      - SYS_ADMIN
    environment: 
      - container=docker
    security_opt: 
      - seccomp:unconfined
    tmpfs: 
      - /run
      - /run/lock
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
        #- /sys/fs/fuse/connections:/sys/fs/fuse/connections
        #- /dev/hugepages:/dev/hugepages
    tty: true
